Home page
AviranBac/Spic pull request #4
Opened 2023-03-17 14:54 UTC by itzhak-Israeli

2023-03-18 11:11 UTC, AviranBac requested changes

2023-03-18 11:11 UTC, AviranBac commented on client/src/Components/ClickableBox.tsx
> +    const title = replaceEngToHeb(categoryName);
After communicating with backend and getting the image urls, you won't need `getImageByCategory`, and the `categoryName` will already be in Hebrew, so `replaceEngToHeb` will be removed as well.

2023-03-18 11:11 UTC, AviranBac commented on client/src/Screens/HomeScreen.tsx
> +const CATEGORIES_LIST: [string, string[]][] = [['play', []], ['dress', []]];
As we spoke, make something like a service that will be responsible for fetching the categories from the backend (using `axios`).  The response will only include categories (without subcategories).

2023-03-18 11:11 UTC, AviranBac commented on client/src/ButtomBar/BottomBar.tsx
> +    RECENT: 'בשימוש נפוץ',
`RecentScreen` -> `CommonlyUsedScreen`, rename the relevant screen

2023-03-18 11:11 UTC, AviranBac commented on client/src/Components/ClickableBox.tsx
> +        <View style={{flexBasis: '50%', alignItems:'center', justifyContent:'center'}}>
Move `flexBasis`, `alignItems`, `justifyContent` to the parent (`HomePage`)
You hard-codedly duplicated 6 items per category here but in reality there'll be only one `TouchableOpacity` in here, without a `View`

Also, according to the mockup, there should be 4 items in each row

2023-03-18 11:11 UTC, AviranBac commented on client/src/Components/ClickableBox.tsx
> +            <TouchableOpacity>
In general, try to make the `TouchableOpacity` look like the mockup we originally did:
border for the picture, text under it.. whatever you can
In the end of the project there's a section in which we need to make a comparison between the mockup and the end-product, so it's important we stay consistent as much as possible :)

2023-03-18 11:11 UTC, AviranBac commented on client/package.json
>      "web": "expo start --web"
In `app.json`:
Change `"orientation": "portrait"` to `"orientation": "default"`.
Now you can check how the app looks in landscape display whenever you flip your device.

2023-03-18 18:21 UTC, itzhak-Israeli commented on client/src/AppBar/MainAppBar.tsx
> +        <AppBar style={{direction: "rtl", backgroundColor: '#c7f5fe', paddingTop: (Platform.OS === 'ios') ? 20 : 0}}>
for now its ok to leave it like this
I saw this in SO

2023-03-18 18:23 UTC, itzhak-Israeli commented on client/package.json
> +    "react-native-paper": "^5.2.0",
They are currently not in use, but I think that We will need them later

2023-03-19 13:23 UTC, itzhak-Israeli commented on client/src/ButtomBar/BottomBar.tsx
> +            <Tab.Navigator
fix this - add the rtl to the main page

2023-03-19 13:26 UTC, itzhak-Israeli commented on client/src/Components/ClickableBox.tsx
> +export const ClickableBox = ({categoryName, subCategories}: ClickableBoxProps) => {
fix

2023-03-19 13:26 UTC, itzhak-Israeli commented on client/src/Components/ClickableBox.tsx
> +    const title = replaceEngToHeb(categoryName);
ok

2023-03-19 13:27 UTC, itzhak-Israeli commented on client/src/Screens/HomeScreen.tsx
> +const CATEGORIES_LIST: [string, string[]][] = [['play', []], ['dress', []]];
ok will be fixed when the back will be ready

2023-03-19 14:43 UTC, itzhak-Israeli commented on client/src/AppBar/MainAppBar.tsx
> +export const MainAppBar = () => {
ok

2023-03-20 12:35 UTC, itzhak-Israeli commented on client/src/Screens/HomeScreen.tsx
> +                    <Text style={{fontSize: 25}}>
fix and add styled components

2023-03-25 18:23 UTC, AviranBac approved these changes

2023-03-25 18:23 UTC, merged