feat: add category start of sentence
AviranBac/Spic pull request #9
Opened 2023-04-06 09:52 UTC by talshuker

2023-04-07 13:58 UTC, amittes approved these changes, later dismissed

2023-04-08 18:52 UTC, AviranBac requested changes

2023-04-08 18:52 UTC, AviranBac commented on client/src/services/categories.service.ts
> +export interface Category {
After merge conflicts, remove this because it'll be defined in a separate model file

2023-04-08 18:52 UTC, AviranBac commented on client/src/services/categories.service.ts
> +            const gender : Gender | undefined = store.getState().auth.userSession?.gender;
Maybe send gender as a parameter from the component (using `useAppSelector(selectGender)`)
Then you won't need to do `store.getState().auth.userSession?.gender`

2023-04-08 18:52 UTC, AviranBac commented on server/src/db/schemas/category.schema.ts
> +    items: Array<Item>
Remove `items`.
Go over `main` branch and make sure the schemas are the same (you don't need to change any schema from `main`)

2023-04-08 18:52 UTC, AviranBac commented on server/src/db/dal/init-db.ts
> +    sentenceBeginning: 'אני רוצה ללבוש',
You have two `sentenceBeginning` fields :O
"מחכה ששוקר תסיים לעשות התחלות משפטים"
חחחח

2023-04-09 11:08 UTC, AviranBac approved these changes

2023-04-09 11:09 UTC, merged